let elements = {

    'a': 'HTMLAnchorElement',
    'area': 'HTMLAreaElement',
    'br': 'HTMLBRElement',
    'base': 'HTMLBaseElement',
    'body': 'HTMLBodyElement',
    'button': 'HTMLButtonElement',
    'canvas': 'HTMLCanvasElement',
    'content': 'HTMLContentElement',
    'dl': 'HTMLDListElement',
    'data': 'HTMLDataElement',
    'datalist': 'HTMLDataListElement',
    'div': 'HTMLDivElement',
    'document': 'HTMLDocument',
    'fieldset': 'HTMLFieldSetElement',
    'form': 'HTMLFormElement',
    'framset': 'HTMLFrameSetElement',
    'hr': 'HTMLHRElement',
    'head': 'HTMLHeadElement',
    'h': 'HTMLHeadingElement',
    'html': 'HTMLHtmlElement',
    'iframe': 'HTMLIFrameElement',
    'img': 'HTMLImageElement',
    'input': 'HTMLInputElement',
    'keygen': 'HTMLKeygenElement',
    'li': 'HTMLLIElement',
    'label': 'HTMLLabelElement',
    'legend': 'HTMLLegendElement',
    'link': 'HTMLLinkElement',
    'map': 'HTMLMapElement',
    'media': 'HTMLMediaElement',
    'meta': 'HTMLMetaElement',
    'mod': 'HTMLModElement',
    'ol': 'HTMLOListElement',
    'object': 'HTMLObjectElement',
    'optgroup': 'HTMLOptGroupElement',
    'option': 'HTMLOptionElement',
    'output': 'HTMLOutputElement',
    'p': 'HTMLParagraphElement',
    'param': 'HTMLParamElement',
    'picture': 'HTMLPictureElement',
    'pre': 'HTMLPreElement',
    'quote': 'HTMLQuoteElement',
    'script': 'HTMLScriptElement',
    'select': 'HTMLSelectElement',
    'shadow': 'HTMLShadowElement',
    'span': 'HTMLSpanElement',
    'style': 'HTMLStyleElement',
    'caption': 'HTMLTableCaptionElement',
    'td': 'HTMLTableCellElement',
    'col': 'HTMLTableColElement',
    'table': 'HTMLTableElement',
    'th': 'HTMLTableCellElement',
    'tr': 'HTMLTableRowElement',
    'template': 'HTMLTemplateElement',
    'textarea': 'HTMLTextAreaElement',
    'title': 'HTMLTitleElement',
    'ul': 'HTMLUListElement',
    'unknown': 'HTMLUnknownElement',

    'article': 'HTMLElement',
    'aside': 'HTMLElement',
    'bdi': 'HTMLElement',
    'details': 'HTMLDetailsElement',
    'dialog': 'HTMLDialogElement',
    'figcaption': 'HTMLElement',
    'figure': 'HTMLElement',
    'footer': 'HTMLElement',
    'header': 'HTMLElement',
    'main': 'HTMLElement',
    'mark': 'HTMLElement',
    'menuitem': 'HTMLUnknownElement',
    'meter': 'HTMLMeterElement',
    'nav': 'HTMLElement',
    'progress': 'HTMLProgressElement',
    'rp': 'HTMLElement',
    'rt': 'HTMLElement',
    'ruby': 'HTMLElement',
    'section': 'HTMLElement',
    'summary': 'HTMLElement',
    'time': 'HTMLTimeElement',
    'wbr': 'HTMLElement',

    'svg': 'SVGElement',
    'audio': 'HTMLAudioElement',
    'embed': 'HTMLEmbedElement',
    'source': 'HTMLSourceElement',
    'track': 'HTMLTrackElement',
    'video': 'HTMLVideoElement',

};

export {
    elements
};
