
let w = System.global.window;

export default {

	// regular tag
	'a': w.HTMLAnchorElement,
	'area': w.HTMLAreaElement,
	'br': w.HTMLBRElement,
	'base': w.HTMLBaseElement,
	'body': w.HTMLBodyElement,
	'button': w.HTMLButtonElement,
	'canvas': w.HTMLCanvasElement,
	'content': w.HTMLContentElement,
	'dl': w.HTMLDListElement,
	'data': w.HTMLDataElement,
	'datalist': w.HTMLDataListElement,
	'div': w.HTMLDivElement,
	'document': w.HTMLDocument,
	'fieldset': w.HTMLFieldSetElement,
	'form': w.HTMLFormElement,
	'framset': w.HTMLFrameSetElement,
	'hr': w.HTMLHRElement,
	'head': w.HTMLHeadElement,
	'h': w.HTMLHeadingElement,
	'html': w.HTMLHtmlElement,
	'iframe': w.HTMLIFrameElement,
	'img': w.HTMLImageElement,
	'input': w.HTMLInputElement,
	'keygen': w.HTMLKeygenElement,
	'li': w.HTMLLIElement,
	'label': w.HTMLLabelElement,
	'legend': w.HTMLLegendElement,
	'link': w.HTMLLinkElement,
	'map': w.HTMLMapElement,
	'media': w.HTMLMediaElement,
	'meta': w.HTMLMetaElement,
	'mod': w.HTMLModElement,
	'ol': w.HTMLOListElement,
	'object': w.HTMLObjectElement,
	'optgroup': w.HTMLOptGroupElement,
	'option': w.HTMLOptionElement,
	'output': w.HTMLOutputElement,
	'p': w.HTMLParagraphElement,
	'param': w.HTMLParamElement,
	'picture': w.HTMLPictureElement,
	'pre': w.HTMLPreElement,
	'quote': w.HTMLQuoteElement,
	'script': w.HTMLScriptElement,
	'select': w.HTMLSelectElement,
	'shadow': w.HTMLShadowElement,
	'span': w.HTMLSpanElement,
	'style': w.HTMLStyleElement,
	'caption': w.HTMLTableCaptionElement,
	'td': w.HTMLTableCellElement,
	'col': w.HTMLTableColElement,
	'table': w.HTMLTableElement,
	'th': w.HTMLTableCellElement,
	'tr': w.HTMLTableRowElement,
	'template': w.HTMLTemplateElement,
	'textarea': w.HTMLTextAreaElement,
	'title': w.HTMLTitleElement,
	'ul': w.HTMLUListElement,
	'unknown': w.HTMLUnknownElement,

	//html5 tags
	'article': w.HTMLElement,
	'aside': w.HTMLElement,
	'bdi': w.HTMLElement,
	'details': w.HTMLDetailsElement,
	'dialog': w.HTMLDialogElement,
	'figcaption': w.HTMLElement,
	'figure': w.HTMLElement,
	'footer': w.HTMLElement,
	'header': w.HTMLElement,
	'main': w.HTMLElement,
	'mark': w.HTMLElement,
	'menuitem': w.HTMLUnknownElement,
	'meter': w.HTMLMeterElement,
	'nav': w.HTMLElement,
	'progress': w.HTMLProgressElement,
	'rp': w.HTMLElement,
	'rt': w.HTMLElement,
	'ruby': w.HTMLElement,
	'section': w.HTMLElement,
	'summary': w.HTMLElement,
	'time': w.HTMLTimeElement,
	'wbr': w.HTMLElement,

	'svg': w.SVGElement,

	// Video / Audio elements
	'audio': w.HTMLAudioElement,
	'embed': w.HTMLEmbedElement,
	'source': w.HTMLSourceElement,
	'track': w.HTMLTrackElement,
	'video': w.HTMLVideoElement,

}
